export const FETCH_LOADING = "FETCH_LOADING";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_FAILURE = "FETCH_FAILURE";
export const BLOG_VIEW="BLOG_VIEW"
export const BLOG_LOADING = "BLOG_LOADING";
export const BLOG_SUCCESS = "BLOG_SUCCESS";
export const BLOG_FAILURE = "BLOG_FAILURE";
