export const dummyData = [
  {
    id: 1,
    address: "SteinstraB 11",
    postcode: "22303",
    property: "Flat",
    rooms: "5",
    area: "48",
    checked: false,
  },
  {
    id: 2,
    address: "HimmeistraBe 2",
    postcode: "24303",
    property: "House",
    rooms: "8",
    area: "78",
    checked: false,
  },
  {
    id: 3,
    address: "Alte Schleuse 23",
    postcode: "26503",
    property: "Terraced house",
    rooms: "7",
    area: "38",
    checked: false,
  },
  {
    id: 4,
    address: "Lahore 32",
    postcode: "34503",
    property: "Semi-detached",
    rooms: "6",
    area: "68",
    checked: false,
  },
  {
    id: 5,
    address: "Karachi 34",
    postcode: "32303",
    property: "Villa",
    rooms: "12",
    area: "54",
    checked: false,
  },
  {
    id: 6,
    address: "Punjab C23",
    postcode: "15203",
    property: "Farmhouse",
    rooms: "43",
    area: "99",
    checked: false,
  },
  {
    id: 7,
    address: "Punjab C23",
    postcode: "15203",
    property: "Farmhouse",
    rooms: "43",
    area: "99",
    checked: false,
  },
];
